---
booktitle: Proceedings of the Seventeenth International Conference on Artificial Intelligence
  and Statistics
volume: 33
year: '2014'
start: 2014-04-22
end: 2014-04-25
published: 2014-04-02
shortname: AISTATS
sections:
- name: preface
  title: Preface
- name: notable
  title: Notable Papers
- name: default
  title: Regular Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: AISTATS-2014
month: 0
cycles: false
editor:
- given: Samuel
  family: Kaski
- given: Jukka
  family: Corander
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Seventeenth International Conference on Artificial Intelligence and Statistics
    Held in Reykjavik, Iceland on 22-25 April 2014

  Published as Volume 33 by the Proceedings of Machine Learning Research on 02 April 2014.

  Volume Edited by:
    Samuel Kaski
    Jukka Corander

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 22--25 Apr
url: http://proceedings.mlr.press
baseurl: "/v33"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v33
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Artificial Intelligence and Statistics
  url: http://www.aistats.org/aistats2014/
  location: Reykjavik, Iceland
  dates:
  - 2014-04-22
  - 2014-04-23
  - 2014-04-24
  - 2014-04-25
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v33.bib
---
